markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: imjok00
author: "jokjok"
email: sunhuang00@126.com
name: "imjok00"
url: http://www.imjok.com
domain: www.imjok.com
all_categories: [
["juc", "java并发包","/posts/juc.html"], 
["collection", "java数据结构","/posts/collection.html"],
["spring", "Spring解析","/posts/spring.html"], 
["other", "人生杂谈","/posts/other.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

plugins:
 - jekyll-paginate
